#!/usr/bin/env python3
#zadanie 24

mojalicz=56
def insit(s):
    try:
    	int(s)
    	return True
    except ValueError:
    	return False
print('Zgadnij liczbe. Masz 7 prob')
i=0
while i<7:
    i+=1
    proba=input("wprowadz liczbe calkowita")
    p=insit(proba)
    if p==False:
    	print("wprowadzona nie calkowita liczba")
    else:
    	pp=int(proba)
    	if mojalicz==pp:
    	    print("Brawo Ty! Zgadles liczbe")
    	    break
    	elif mojalicz>pp:
    	    print("wiecej")
    	else:
    	    print("mniej")