#!/usr/bin/env python3
#zadanie 23

mojalicz=37
def insit(s):
    try:
    	int(s)
    	return True
    except ValueError:
    	return False
print('Zgadnij liczbe. Masz 10 prob')
for i in range(10):
    proba=input("wprowadz liczbe calkowita")
    p=insit(proba)
    if p==False:
    	print('wprowadzona nie calkowita liczba')
    else:
    	pp=int(proba)
    	if pp==mojalicz:
    	    print("Brawo! Zgadles liczbe")
    	    break
    	elif mojalicz>pp:
    	    print("wiecej")
    	else:
    	    print("mniej")