#!/usr/bin/env python3
#zadanie 21

#level=4
#print("x" *4)
#for i in range(2):
#    print("x","" *2,"x")
#print("x" *4)

level=int(input("Podaj wymiar kwadratu"))
print("x " *level)
for i in range(level-2):
    print("x ","  "*(level-3),"x")
print("x "*level)