#!/usr/bin/env python3
print('Hello World!')
print('Jestem','tu')
'sep="separator"'
print('Jestem','tu',sep="")
print('Jestem','tu',sep='XXX')
print('Jestem','tu',sep=' ')
print("Co u ciebie?")
print('Co','u','ciebie?',sep=' ')




